package Client;

public enum Command {
    Login,
    SignUp,
    ForgotPassword,
    Username_unique,
    Publish_Post,
    LoadTimeLine,
    LikePost,
    AddComment,
    Follow,
    GetInfo,
    LoadSearchTable,
    UnFollow,
    UpdateProfile,
    rePost,
    LoadPersonalTimeLine,
    SaveSecondPassword,
    LoadUserDirect,
    ChangePassword,
    SendMessage,
    LoadChatPage,
    Block,
    TrashText, UpdateData, Mute, UnMute, UnBlock,
}
